name: Build and Test .NET 9 App // coloque o nome q vc quiser

# // 
# isso chamamos de triggers da nossa pipeline como um todo
# triggers é uma acao que vai gerar uma reacao na nossa pipeline
on:
   push:
      branches:
         - main
  #  pull_requests:
  #     branches:
  #        - main
   workflow_dispatch:
#  isso chamamos de triggers
#    //

env:
  SHOULD_PUBLISH: true

jobs:

  build:
    # // seria a vm
    runs-on: ubuntu-latest 
    # // seria a vm

    if: ${{ github.ref == 'refs/heads/main' }}

    steps:
    - name:  Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET 9
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name:  Build the project
      run: dotnet build --configuration Release --no-restore

    - name:  Publish the project
      # if: env.SHOULD_PUBLISH == 'true'
      if: env.SHOULD_PUBLISH == 'true'
      run: dotnet publish --configuration Release --output ./publish
       
    # - name:  Upload artifacts
    #   uses:  actions/upload-artifact@v4
    #   with:
    #     name: published-artifacts

  
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
        
      - name: Restore dependencies
        run: dotnet restore

      - name: Run tests
        run: dotnet test --configuration Release --no-build --verbosity normal

  deploy:
    runs-on: ubuntu-latest
    needs: [build, test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy application
        run: |
          echo "Deploying application"